[package]
name = "quark"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["proc-macros"]

[dependencies]
# Monoxide crates
proc-macros = { path = "proc-macros" }

# External dependencies
dashmap = "6.1.0"
rustc-hash = "2.0.0"
openxr = { version = "0.19.0", default-features = false }
